### PR TITLE
A rudimentary archival banner added

### PR DESCRIPTION
**Pull request by ibnesayeed**
This PR provides initial implementation of #144.

### CODE REVIEW

**Comment by ibnesayeed** [comment]
@machawk1 can you look into this CI Build failing issue due to flake8 test dependency?

**Comment by machawk1** [comment]
It looks like the issue was intermittent, @ibnesayeed. I restarted the build and it passed.

**Comment by ibnesayeed** [comment]
It looks like those tests passed.

**Comment by machawk1** [comment]
@ibnesayeed Should the banner be displaying when viewing URI-Ms with this PR? I was unable to see the banner on the froggie memento. I anticipated seeing a banner like you have on the reconstructive demo page.

**Comment by ibnesayeed** [comment]
> @ibnesayeed Should the banner be displaying when viewing URI-Ms with this PR? I was unable to see the banner on the froggie memento. I anticipated seeing a banner like you have on the reconstructive demo page.

Yes, that is the purpose of this PR. I tested it with the default sample file before pushing changes and creating this PR. Please make sure that the SW is updated. It should show `Reconstructive:0.4` in the console.

**Comment by machawk1** [comment]
Again, disregard the above. Chrome had propagated the old serviceworker/reconstructive from a previous incognito session. I can now see the banner.

**Comment by ibnesayeed** [comment]
Yes, I tested it with the froggie and I can see it.

**Pull request merged**
