### PR TITLE
Update TravisCI to use go-ipfs 0.5.1

### PR DESCRIPTION
**Pull request by machawk1**
@ibnesayeed Can you verify that only these two files need to be changed?

### CODE REVIEW

**Comment by ibnesayeed** [comment]
Yes, generally that's all we need to change for IPFS version bump. However, it looks like the pycodestyle is not happy with the use of `l` as the variable in (which has nothing to do with this issue):

https://github.com/oduwsdl/ipwb/blob/b8c1ea350618ab1bdf6abba67f99316303f53ce9/ipwb/indexer.py#L151

**Comment by machawk1** [comment]
Odd that this surfaced with this PR, maybe a change in pycodestyle. I will make the change, update this PR, then give you a ping before merging.

**Comment by machawk1** [comment]
Yep, I updated my local pycodestyle from 2.5.0 to 2.6.0 and sure enough the same linting issue surfaced.

**Comment by ibnesayeed** [comment]
Yes, that was my guess too, it was something newly introduced to the linter.

**Pull request merged**
