### PR TITLE
Fix Markdown formatting issues after conversion from RST

### PR DESCRIPTION
**Pull request by ibnesayeed**
Mainly fixed language annotations in code blocks as noted in #399.

### CODE REVIEW

**Comment by machawk1** [comment]
I have been aware of the latter (PyPi versioning) issue since we started pushing it there and encountered a date with a leading 0. The leading 0 keeps lexical positioning sorting, so I have retained using that style despite PyPi's behavior.

**Comment by ibnesayeed** [comment]
PyPi should take version number as opaque string though.

**Comment by machawk1** [comment]
I completely agree though maybe they do it on the PEP-440 rationale:

> All numeric components MUST be interpreted and ordered according to their numeric value, not as text strings.

**Comment by machawk1** [comment]
On the contrary, same PEP:

> All release segments involved in the comparison MUST be converted to a consistent length by padding shorter segments with zeros as needed.

**Comment by ibnesayeed** [comment]
I came to know the reasoning behind this because they wanted to ensure `00 == 0` in version numbers as per https://github.com/pypa/setuptools/issues/302#issuecomment-202915790.

**Pull request merged**
