### PR TITLE
[WIP] Fix plurality of mementos and resources on main replay page. Closes #534

### LINKED ISSUE #534: Plurality issue in the URI listing in the replay UI
screen shot 2018-08-27 at 11 57 17 am

It should be "1 memento of 1 resources with 0 HTML pages listed"

### PR DESCRIPTION
**Pull request by machawk1**
@ibnesayeed Kudos on the implementing the templating system, btw!

### CODE REVIEW

**Comment by machawk1** [comment]
@ibnesayeed That would be a good improvement but for now, this fixes the issue described in #534.

**Comment by machawk1** [comment]
`inflect` is also GPLv3, @ibnesayeed (related: #382)

**Comment by ibnesayeed** [comment]
I will leave the decision of merging this PR in its current state or otherwise to you discretion because I am not a big fan of hacky approaches on every step that pile up and make maintenance difficult (and invite more hacks for every new change).

**Comment by ibnesayeed** [comment]
> inflect is also GPLv3

We can avoid using that, but still move the pluralization logic into Context Processors.

**Comment by machawk1** [comment]
@ibnesayeed Ok, I'll get a little more familiar with Flask's context processors and implement that with this same PR.

**Comment by machawk1** [comment]
`./ipwb/replay.py:73:5: E731 do not assign a lambda expression, use a def` needs to be fixed before we merge this.

**Pull request merged**
