### PR TITLE
Remove duplicate memento route

### LINKED ISSUE #342: Remove duplicate endpoints with similar logic
Currently, `replay.py` has two methods `showMemento` and `showMementoAtDatetime` that are being served at `/memento/<datetime>/<urir>` not at `/<datetime>/<urir>` respectively. The latter has duplicate behavior with less functionalities. I think the later should be removed completely, but before that we can set a redirect from one to the other to make sure other things are not breaking. More discussion on this can be found in #339. Current SW implementation actually performs this rerouting on the client side anyway, but for Reconstructive (#338) to be used efficiently, we need to remove this duplicate behavior.

### PR DESCRIPTION
**Pull request by ibnesayeed**
This should fix #342. A related ticket #450 is closed already.

### CODE REVIEW

**Comment by machawk1** [comment]
@ibnesayeed Travis is reporting that tests are failing with your PR. Can you have a look at this?

**Comment by ibnesayeed** [comment]
I was looking into it. I think I know what's wrong here. A fix is on the way.

**Comment by machawk1** [comment]
@ibnesayeed Once you fix the pycodestyle issue reported, we should be able to merge this.

**Comment by ibnesayeed** [comment]
This looks like passing now. However, in future we need to be vigilant about places where old style memento links might be generated.

**Pull request merged**
