### PR TITLE
Add GH Workflow for cross-platform tests

### PR DESCRIPTION
**Pull request by ibnesayeed**
This utilizes matrix of OSes, Python and IPFS versions to perform tests of various combinations.

### CODE REVIEW

**Comment by ibnesayeed** [comment]
It looks like Windows tests are halting. We need to test it manually on a Windows machine as following:

* Install Windows Server 2019
* Ensure Bash and cURL are installed in it
* Install NodeJS 12
* Install Python 3.7 or 3.8
* Install IPFS (i.e., download and extract the binary and set PATH accordingly)
* Run IPFS daemon
* Run ipfs cat on the welcome file
* Clone IPWB
* Run IPWB tests

**Comment by ibnesayeed** [comment]
This aims to resolve #630, but Windows environment is not behaving well. I think we can move with what we have working here and revisit Windows later.

**Comment by ibnesayeed** [comment]
> @machawk1: 3.8 is problematic on some systems

That's why we are testing 3.7 and 3.8 both on various platforms using matrix, but inside a Docker container we can more confidently go for the latest Python.

**Comment by ibnesayeed** [comment]
@machawk1 should we abstract out the task of linting the code as a separate job and not repeat it in every matrix environment?

**Comment by machawk1** [comment]
@ibnesayeed Yes, only need to lint in one environment. No need to repeat.

**Comment by ibnesayeed** [comment]
@machawk1 this is in good shape (other than Windows, which is commented out for now).

**Comment by machawk1** [comment]
@ibnesayeed I should have some time to explore and evaluate this tomorrow (May 14) afternoon.

**Comment by ibnesayeed** [comment]
It looks like the `codecov` utility is a not an independent tool, but a way to submit results to codecov.io for reporting, hence removing it from the workflow.

**Comment by ibnesayeed** [comment]
Windows tests are still failing and taking forever to complete, likely due to IPWB bugs (because the action otherwise runs tests on all platforms fine).

**Pull request merged**
