### PR TITLE
Renamed deploy.sh to release.sh and used UTC time

### PR DESCRIPTION
**Pull request by ibnesayeed**
This PR improves #353

### CODE REVIEW

**Comment by ibnesayeed** [comment]
I have a different opinion here. The script is not deploying anything, it is releasing a new version instead. That said, it does not have the timezone information in it, so it could be problematic in some situations. Suppose, I visit India (which happens to be 9.5 or 10.5 hours ahead of the Eastern Time) and I publish a new version by running that script. A few minutes later you make some changes and push another release using the same script. This last version number is going to have an earlier time (and perhaps a day earlier too). Even if that situation is far fetched, it illustrates the problem of not making it timezone-neutral. These version numbers are for users, which we don't expect them to have the same TZ as ours or know that which TZ the code was released form.

**Comment by machawk1** [comment]
I agree on the renaming of the script.

How about we pin it where it always uses EST instead of the user's timezone? That's as arbitrary as GMT but it's consistent with every version released so far.

**Comment by ibnesayeed** [comment]
While sticking it to any timezone would be much better than using local time at run time. However, UTC (not GMT) is not as arbitrary as EST. That is a time that is default for the web in many protocols, including HTTP. It does not necessarily attach a geolocation with the time. Sticking it to EST will have issues of a later version counted as an earlier one on the night when clocks go back an hour and if DST is not considered then for a fair part of the year release time will be off by an hour. With that said, I think we should go for UTC. The past releases will become inconsistent, but we should not hurt future ones because of the past, especially when it does not have any serious consequences.

**Comment by machawk1** [comment]
@ibnesayeed I'm conceding to your rationale and have merged this PR.

**Comment by ibnesayeed** [comment]
And for the first time we have dated releases on [DockerHub](https://hub.docker.com/r/oduwsdl/ipwb/builds/).

**Pull request merged**
