### PR TITLE
Separate admin interface

### PR DESCRIPTION
**Pull request by ibnesayeed**
A step towards separating admin interface from the landing page (as per #213). Styling and authentication can be added later.

### CODE REVIEW

**Comment by machawk1** [comment]
@ibnesayeed I tested this and could not hit the `/admin` endpoint in a browser. Are you able to?

**Comment by ibnesayeed** [comment]
Yes, when I implemented it, I was able to access admin page. Can you try clearing cache and service worker first? Meanwhile I will test it again to see if it still works.

**Comment by machawk1** [comment]
I restarted Chrome and opened a new incognito and still get a 404 when I access `localhost:5002/admin`.

Using ef26e2c4807b08b7a9a11de0382f3abc6d220fa1

stdout returns
```
Could not find admin)/ in CDXJ at /tmp/E6KM74U56W13.cdxj
CDXJ Line: None
Getting CDXJ Lines with admin in /tmp/E6KM74U56W13.cdxj
Could not find admin)/ in CDXJ at /tmp/E6KM74U56W13.cdxj
CDXJ lines with URI-R at admin
[]
Getting CDXJ Lines with admin in /tmp/E6KM74U56W13.cdxj
Could not find admin)/ in CDXJ at /tmp/E6KM74U56W13.cdxj
```

**Comment by ibnesayeed** [comment]
Did you re-build the Docker image?

**Comment by ibnesayeed** [comment]
From the logs it looks like it is being treated as a URI-M, which should not be the case.

**Comment by machawk1** [comment]
@ibnesayeed That was the issue...sort of. I was rebuilding the version without the :2 tag. I can access the admin interface now.

This looks like a good start.

**Comment by machawk1** [comment]
Should we wait to merge this until we have the functionality behind the placeholders in-place?

**Comment by ibnesayeed** [comment]
No, I think we can merge it as it is (if it is working as expected). It is currently not being linked from the landing page so people should not notice it.

In a separate PR we can:

* add some styling
* fill in some of the missing placeholders
* remove/move admin functionalities from the landing page and
* link admin interface from the landing page

In a separate PR we can add some sort of authentication to admin page and in another separate PR we can move landing page to templates folder and use built-in templating system as opposed to find and replace technique currently in use in the `index.html` file.

**Pull request merged**
