### PR TITLE
Reconstructive and ReconstructiveBanner updates

### PR DESCRIPTION
**Pull request by ibnesayeed**
Updated Reconstructive and ReconstructiveBanner files to their latest version. Documentation comments are now removed and the banner has a more precise relative datetime along with an option to toggle between relative and absolute datetime display.

### CODE REVIEW

**Comment by machawk1** [comment]
? cursor is not shown on hover of precise date.

**Comment by ibnesayeed** [comment]
> ? cursor is not shown on hover of precise date.

That was intentional, because there is no surprise hidden when one goes back to the less precise representation,

**Comment by machawk1** [comment]
If I toggle the display then visit the temporally adjacent memento, it reverts. This is frustrating and counter-intuitive.

**Comment by ibnesayeed** [comment]
Again, you are talking about keeping the state over the session which is doable using something like storing state in local storage, but the essence of that option is different. Once a user is navigated to a new memento, it is an independent memento. Current philosophy is to show a gralnceable time difference with the option to uncover a precise datetime when demanded for it. Users' intent may or may not be to retain the state across navigation.

**Comment by ibnesayeed** [comment]
While I do not disagree that there can be use niche cases where retaining this state might be useful for some users, at this point I do not see it as a preference, but an additional detail that user wanted to peek in (that is signified by the `?` cursor which indicates there is something more here). Some sites have keyword definitions or help tips associated with certain page elements which can be revealed when needed. If a user utilizes them and reloads to page or navigate to another page on the same site and they retain the open sate of those info boxes, it would be counter-intuitive. Similarly, if a site has a notification menu that can be be opened to see there were five new updates. The user clicks on one of those and has four more to go, then the site might not want to keep the notification menu open on each page load.

We expect that most of the users should open a memento to see what in the archive page. An archival banner is not the primary point of attraction on the page. It is there when it is needed otherwise it should go out of the way. With that in mind, I don't think it is bad to have the simplistic summary as the primary message and details on demand.

**Comment by ibnesayeed** [comment]
Take another example, suppose a user is interested more details about a memento so uses banner in the expanded mode, while in this mode the user reloads the page, clicks on the nav buttons (next/prev/first/last), or enters a new URI-R to navigate to different memento, should we retain the banner in expanded view on the new page load just because the user might want to know more about that age as well? How would we know what is user's intent? Can't we default to what might work for most people and those who need it different can still spare one more click per page.

Internet archive has a drawer in it's banner that can be opened using `About this capture` link in the corner. But once you navigate to a new memento of the same URI-R or a different one, it goes away.

**Comment by ibnesayeed** [comment]
> Aside: let's start complying with Standard JS (#45, #46), particularly re: superfluous semi-colons.

On the other hand I would suggest let's convert any non-Reconstructive code to the semi-colon style as those are minority in this repo. I am now using Babel, a very well-known JS transpiler which continues to use semi-colons by default and the whole MDN documentation uses this practice of including semi-colons in in the modern JS APIs.

**Comment by ibnesayeed** [comment]
Changes in #520 took care of the state persistence feature and more.

**Pull request merged**
